# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 30e0d655ca49da3f7ae5b309f180528166dd36853b4aabed8bedf4abb2f7bda151cfd67da7f1b20e527b85ecb2a189d48613c0775e7ebc0984ac42c2eb409413

test:
  secret_key_base: 13738e46c86b27d144caa1810be1681170703cc0651f3136576af2ffd83747c4a7fd37c841a624664428c6d5c9af6e4cf2f07c6ade9d1ebfc08b8ba7637c64f1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
